[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Mainnet forking configuration
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

# Fork configuration for testing against real Arbitrum contracts
[profile.default.fork]
url = "${MAINNET_RPC_URL}"
block_number = 21000000  # Recent block for consistent testing

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
